### ISSUE TITLE
/spot/v4/query/open-orders API returns no data while others function correctly

### ISSUE THREAD

**Issue by HEGADE** [bitmartexchange/bitmart-postman-api#1]
I'm unable to retrieve order details using the /spot/v4/query/open-orders API endpoint. All other API endpoints I've tested are working as expected.(and I'm using right credentials also)
Could you please help investigate why this specific API may be returning empty data?

**Comment by 11101171** [comment]
This endpoint will only query orders whose status is new or partially filled.

**Comment by HEGADE** [comment]
so how can i get the order book data, can you please mention the right API for it, with the parameter needed?

> This endpoint will only query orders whose status is new or partially filled.

**Comment by HEGADE** [comment]
![image](https://github.com/bitmartexchange/bitmart-postman-api/assets/60566946/712f9b4c-80d9-4bd3-8375-92a91a528ddf)
also , if don't specify the end time and start time by default it should show the 7-day data right? but why this recWindow error, what did I wrong here?

**Comment by 11101171** [comment]
@HEGADE
1.Yes, if the time range startTime and endTime are not filled in, the data of the last 7 days will be displayed by default. 
2.The recvWindow error occurs mostly because the time from your request to the server's acceptance exceeds your setting. This often occurs when your network environment is poor.
